export enum PieceJointeFiche {
    pieceafournir = "PIÈCES A FOURNIR (avant la signature du contrat)",
    diplome = "Diplômes",
    cv = "Curriculum vitae",
    ficheAllocationFamiliale = "Fiche allocation familiale CNPS (si immatriculé)",
    copie05PremierePagePasseport = "Copie des 5 premières pages du passeport (si nécessaire)",
    photoIdentite = "Photo identité (03)",
    photo1 = "Photo 1",
    photo2 = "Photo 2",
    photo3 = "Photo 3",
    planLocalisation = "Plan de localisation",
    livretCNPS = "Livret CNPS ou fiche signalétique (si immatriculé)",
    copieCertifieActeMariage = "Copie certifiée acte de mariage sans timbre pour CNPS",
    copieCertifieActeNaissance = "Copie certifiée acte de naissance de l'employé, conjoint(e)/enfants légitimes sans timbre pour CNPS",
    extraitCasierJudiciaire = "Extrait de casier judiciaire N° 3 (datant de 3 mois)",
    copieRIB = "Copie RIB (Relevé d'Identité bancaire)",
    copieCertifieCNI = "Copie certifiée de la CNI",
    certificatTravail = "Certificat de travail",
}
